# config/meta.yml

meta_product_name: "RoomBloom"
meta_title: "RoomBloom - Shuffle Your Space"
meta_description: " Start your redecorating journey with only the click of a few buttons to create your personalized moodboard. Stimulate your creativity and feel empowered to change your space without feeling overwhelmed.

"
meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"  required for Twitter Cards
